//! Every value an operator sets, in one file's worth of structs. No field has
//! a default: a missing limit is a deployment mistake, not a value to guess.

use std::collections::HashSet;
use std::path::PathBuf;

use metsuke::envelope::PoolId;
use serde::Deserialize;

/// The whole config file: where to listen, where the two stores live, and the
/// ingest limits under `[ingest]`.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ServerConfig {
    /// `host:port` to bind, plain HTTP (what fronts it: `http`).
    pub listen: String,
    /// The replay counter database (ADR 0002). Created if absent.
    pub counters_path: PathBuf,
    pub archive: ArchiveConfig,
    pub ingest: IngestConfig,
}

/// Where accepted submissions go. S3 is what production runs (ADR 0005).
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum ArchiveConfig {
    Filesystem { root: PathBuf },
    S3(S3Config),
}

/// The bucket and how long the server waits on it. Credentials are not here —
/// they come from the process environment, which is what keeps this file
/// Nix-managed and public.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct S3Config {
    pub bucket: String,
    pub region: String,
    /// Endpoint URL, bucket name excluded: the AWS regional endpoint in
    /// production, a Garage or MinIO address in a test.
    pub endpoint: String,
    /// Deadline for one S3 request, and how long a signed URL stays usable.
    pub request_timeout_secs: u64,
    /// Extra PUT attempts after the first.
    pub put_retries: u32,
}

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("config does not parse: {0}")]
    Toml(#[from] toml::de::Error),
}

impl ServerConfig {
    pub fn from_toml(text: &str) -> Result<ServerConfig, ConfigError> {
        Ok(toml::from_str(text)?)
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngestConfig {
    /// The participating pools, generated by the allowlist admin command
    /// (ticket metsuke-4zo.9). A pool outside it is rejected before any
    /// cryptography runs.
    pub allowlist: HashSet<PoolId>,
    /// Cap on the compressed body. `intake` measures what it was handed;
    /// `http::read_body` is what refuses an oversized upload before reading
    /// it.
    pub max_body_bytes: u64,
    /// Ceiling the decompressor is allowed to inflate to.
    pub max_decompressed_bytes: u64,
    /// Uploads one pool may make per `rate_limit_window_secs`.
    pub rate_limit_uploads: u32,
    pub rate_limit_window_secs: u64,
    /// How far an envelope timestamp may sit from the server clock in
    /// either direction. The ADR-0002 backstop for lost counter state.
    pub max_timestamp_skew_secs: u64,
}
