//! Every ingest limit an operator sets, in one struct. No field has a
//! default: a missing limit is a deployment mistake, not a value to guess.

use std::collections::HashSet;

use metsuke::envelope::PoolId;
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngestConfig {
    /// The participating pools, generated by the allowlist admin command
    /// (ticket metsuke-4zo.9). A pool outside it is rejected before any
    /// cryptography runs.
    pub allowlist: HashSet<PoolId>,
    /// Cap on the compressed body. `intake` measures what it was handed;
    /// refusing an oversized upload before reading it is the HTTP layer's
    /// job (ticket metsuke-4zo.16).
    pub max_body_bytes: u64,
    /// Ceiling the decompressor is allowed to inflate to.
    pub max_decompressed_bytes: u64,
    /// Uploads one pool may make per `rate_limit_window_secs`.
    pub rate_limit_uploads: u32,
    pub rate_limit_window_secs: u64,
    /// How far an envelope timestamp may sit from the server clock in
    /// either direction. The ADR-0002 backstop for lost counter state.
    pub max_timestamp_skew_secs: u64,
}
